# ====== BUILD ======
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
# build prod Angular 20 (Vite)
RUN npm run build -- --configuration production

# ====== RUNTIME (NGINX) ======
FROM nginx:alpine
# nginx conf otimizada p/ SPA
COPY nginx.conf /etc/nginx/conf.d/default.conf
# copia saída do Angular: dist/<app>/browser -> html
COPY --from=build /app/dist/*/browser/ /usr/share/nginx/html/
EXPOSE 80
